#!/usr/bin/env perl
use strict;
use warnings;

local $/;

my $limit = shift;
$limit = 0 unless defined $limit;

my $src = <>;
$src =~ s{(\s+)([0-9]+)(\s+)}{
    my $n = $2;
    if ($n >= $limit) {
        $1 . sprintf('0x%x', $2) . $3
    } else {
        $1 . $2 . $3
    }
}ge;

print $src;
