#!/usr/bin/env perl
use strict;
use warnings;

my $filename = shift or die "Usage: $0 filename\n";

my $width = 0+ take_2(`sips -g pixelWidth "$filename"`);
$width /= 2;

(my $outfile = $filename) =~ s/(\..+)$/_1x$1/;
system qq{sips --resampleWidth $width "$filename" --out "$outfile"};

sub take_2 { (split /:/, $_[1])[1] }
