#!/usr/bin/env perl
use strict;
use warnings;
use Safe;

local $/;

my $hex = <>;
$hex =~ s/['"]//g;
$hex =~ s/^#.+$//g;
if ($hex =~ /\\x/) {
    my $c = Safe->new;
    print $c->reval(qq{"$hex"});
} else {
    if (length $hex % 2 != 0) {
        $hex = '0' . $hex;
    }
    print pack "H*", $hex;
}
