package docidx

import (
	"strings"
	"testing"
)

// Backticks cannot appear in raw string literals; fixtures write @ instead.
func rstFixture(s string) []byte {
	return []byte(strings.ReplaceAll(s, "@", "`"))
}

// Shaped like Godot's generated class reference (make_rst.py).
const testRSTClassref = `:github_url: hide

.. DO NOT EDIT THIS FILE!!!
.. Generated automatically from Godot engine sources.

.. _class_AStar2D:

AStar2D
=======

**Inherits:** :ref:@RefCounted<class_RefCounted>@

An implementation of A\* for pathfinding.

.. rst-class:: classref-introduction-group

Description
-----------

Long description here.

.. rst-class:: classref-reftable-group

Methods
-------

.. table::
   :widths: auto

   +------+----------------------------------------+
   | void | add_point (id: int, position: Vector2) |
   +------+----------------------------------------+

.. rst-class:: classref-section-separator

----

.. rst-class:: classref-descriptions-group

Property Descriptions
---------------------

.. _class_AStar2D_property_neighbor_filter_enabled:

.. rst-class:: classref-property

:ref:@bool<class_bool>@ **neighbor_filter_enabled** = @@false@@

If true enables filtering of neighbors.

.. rst-class:: classref-section-separator

----

.. rst-class:: classref-descriptions-group

Method Descriptions
-------------------

.. _class_AStar2D_method_add_point:

.. rst-class:: classref-method

|void| **add_point**\ (\ id\: :ref:@int<class_int>@\ )

Adds a new point at the given position.

.. rst-class:: classref-item-separator

----

.. _class_AStar2D_method_clear:

.. rst-class:: classref-method

|void| **clear**\ (\ )

Clears all the points and segments.

.. |void| replace:: :abbr:@void (No return value.)@
`

func TestChunkRSTClassref(t *testing.T) {
	chunks := chunkRST("class_astar2d.rst", rstFixture(testRSTClassref))

	var titles []string
	for _, c := range chunks {
		titles = append(titles, c.Title)
	}
	want := []string{"AStar2D", "Description", "Methods", "neighbor_filter_enabled", "add_point()", "clear()"}
	if len(titles) != len(want) {
		t.Fatalf("titles = %v, want %v", titles, want)
	}
	for i := range want {
		if titles[i] != want[i] {
			t.Fatalf("titles = %v, want %v", titles, want)
		}
	}

	if chunks[0].Anchor != "class_AStar2D" {
		t.Errorf("class anchor = %q", chunks[0].Anchor)
	}
	if chunks[0].Kind != "class" {
		t.Errorf("class kind = %q", chunks[0].Kind)
	}
	if !strings.Contains(chunks[0].Body, "**Inherits:**") {
		t.Errorf("class body = %q", chunks[0].Body)
	}

	if chunks[1].Anchor != "description" {
		t.Errorf("heading anchor fallback = %q", chunks[1].Anchor)
	}
	if !strings.Contains(chunks[2].Body, "| void | add_point (id: int, position: Vector2) |") {
		t.Errorf("table row not collapsed in Methods body: %q", chunks[2].Body)
	}

	prop := chunks[3]
	if prop.Anchor != "class_AStar2D_property_neighbor_filter_enabled" {
		t.Errorf("property anchor = %q", prop.Anchor)
	}
	if prop.Breadcrumbs != "AStar2D > Property Descriptions > neighbor_filter_enabled" {
		t.Errorf("property breadcrumbs = %q", prop.Breadcrumbs)
	}

	method := chunks[4]
	if method.Anchor != "class_AStar2D_method_add_point" {
		t.Errorf("method anchor = %q", method.Anchor)
	}
	if method.Kind != "method" {
		t.Errorf("method kind = %q", method.Kind)
	}
	if method.Breadcrumbs != "AStar2D > Method Descriptions > add_point()" {
		t.Errorf("method breadcrumbs = %q", method.Breadcrumbs)
	}
	if !strings.Contains(method.Body, "Adds a new point") {
		t.Errorf("method body = %q", method.Body)
	}

	for _, c := range chunks {
		for _, junk := range []string{"DO NOT EDIT", ":github_url:", ".. rst-class::", "\n----", ".. |void| replace::", ".. _class_", "+------+"} {
			if strings.Contains(c.Body, junk) {
				t.Errorf("chunk %q body contains %q", c.Title, junk)
			}
		}
	}
}

func TestChunkRSTEnumHeaderKept(t *testing.T) {
	src := rstFixture(`Corners
=======

Enumerations
------------

.. _enum_Control_Corner:

enum **Corner**: :ref:@🔗<enum_Control_Corner>@

.. _class_Control_constant_CORNER_TOP_LEFT:

:ref:@Corner<enum_Control_Corner>@ **CORNER_TOP_LEFT** = @@0@@

Top-left corner.
`)
	chunks := chunkRST("class_control.rst", src)
	var enum *Chunk
	for i := range chunks {
		if chunks[i].Title == "Corner" {
			enum = &chunks[i]
		}
	}
	if enum == nil {
		t.Fatalf("signature-only enum header chunk was dropped: %+v", chunks)
	}
	if enum.Anchor != "enum_Control_Corner" {
		t.Errorf("enum anchor = %q", enum.Anchor)
	}
}

func TestChunkRSTProseBoldAfterTarget(t *testing.T) {
	src := "Head\n====\n\n.. _threading:\n\nGDScript **does not** support real threads here.\n"
	chunks := chunkRST("doc.rst", []byte(src))
	if len(chunks) != 1 {
		t.Fatalf("mid-prose bold after a target must not split: %+v", chunks)
	}
	if !strings.Contains(chunks[0].Body, "**does not** support") {
		t.Errorf("body = %q", chunks[0].Body)
	}
}

func TestChunkRSTCRLF(t *testing.T) {
	src := strings.ReplaceAll("Head\n====\n\nBody.\n\nSub\n---\n\nMore.\n", "\n", "\r\n")
	chunks := chunkRST("doc.rst", []byte(src))
	if len(chunks) != 2 || chunks[0].Title != "Head" || chunks[1].Title != "Sub" {
		t.Fatalf("CRLF input not parsed: %+v", chunks)
	}
	if strings.Contains(chunks[0].Body, "\r") {
		t.Errorf("body retains CR: %q", chunks[0].Body)
	}
}

func TestChunkRSTMultibyteHeading(t *testing.T) {
	src := "概要\n==\n\n本文です。\n"
	chunks := chunkRST("doc.rst", []byte(src))
	if len(chunks) != 1 || chunks[0].Title != "概要" {
		t.Fatalf("rune-length underline rejected: %+v", chunks)
	}
}

func TestChunkRSTBackquotedTarget(t *testing.T) {
	src := ".. _`FAQ: general`:\n\nFAQ\n===\n\nAnswers.\n"
	chunks := chunkRST("doc.rst", []byte(src))
	if len(chunks) != 1 || chunks[0].Anchor != "FAQ: general" {
		t.Fatalf("backquoted target not used as anchor: %+v", chunks)
	}
}

const testRSTOverline = `##########
 Overview
##########

Intro text.

Section A
=========

Body A.

Subsection
----------

Body B.

Deep heading
~~~~~~~~~~~~

Deep body.
`

func TestChunkRSTOverlineAndLevels(t *testing.T) {
	chunks := chunkRST("manual/overview.rst", []byte(testRSTOverline))
	if len(chunks) != 3 {
		t.Fatalf("got %d chunks, want 3: %+v", len(chunks), chunks)
	}
	if chunks[0].Title != "Overview" {
		t.Errorf("chunks[0].Title = %q", chunks[0].Title)
	}
	if chunks[2].Breadcrumbs != "Overview > Section A > Subsection" {
		t.Errorf("chunks[2].Breadcrumbs = %q", chunks[2].Breadcrumbs)
	}
	if !strings.Contains(chunks[2].Headings, "Deep heading") {
		t.Errorf("4th-level heading missing from Headings: %q", chunks[2].Headings)
	}
	if !strings.Contains(chunks[2].Body, "Deep body.") {
		t.Errorf("4th-level body not merged into parent: %q", chunks[2].Body)
	}
}

const testRSTMisc = `Head
====

.. _plain-anchor:

Just a plain paragraph.

.. _godot: https://godotengine.org
   with a continuation line

----

Tail paragraph.

Not a heading
--
`

func TestChunkRSTMisc(t *testing.T) {
	chunks := chunkRST("notes.rst", []byte(testRSTMisc))
	if len(chunks) != 1 {
		t.Fatalf("got %d chunks, want 1: %+v", len(chunks), chunks)
	}
	c := chunks[0]
	if c.Anchor != "head" {
		t.Errorf("anchor = %q; target before non-signature paragraph must be dropped", c.Anchor)
	}
	for _, want := range []string{"Just a plain paragraph.", "Tail paragraph.", "Not a heading"} {
		if !strings.Contains(c.Body, want) {
			t.Errorf("body missing %q: %q", want, c.Body)
		}
	}
	for _, junk := range []string{"godotengine.org", "continuation line", "----"} {
		if strings.Contains(c.Body, junk) {
			t.Errorf("body contains %q: %q", junk, c.Body)
		}
	}
}
